namespace Snake
{
    public static class Levels
    {
        public const string mapWithPlayerTerrain = @"
WWWWWWWWWWWWWWWWWWW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNSNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WWWWWWWWWWWWWWWWWWW";

        public const string mapWithDelievery = @"
WWWWWWWWWWWWWWWWWWW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNSNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNBNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNDNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WWWWWWWWWWWWWWWWWWW";

        public const string mapWithTwoSnakes = @"
WWWWWWWWWWWWWWWWWWW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNSNNNNNNNNNNNSNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WWWWWWWWWWWWWWWWWWW";
    }
}
