namespace Snake
{
    public static class Levels
    {
        public const string OnePlayerBorderMap = @"
WWWWWWWWWWWWWWWWWWW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNSNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WWWWWWWWWWWWWWWWWWW"; 
        
        public const string OnePlayerMap = @"
NNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNN
NNNNNNNNNSNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNN";


        public const string OnePlayerDeliveryMap = @"
WWWWWWWWWWWWWWWWWWW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNSNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNBNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNDNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WWWWWWWWWWWWWWWWWWW";

        public const string TwoPlayersBorderMap = @"
WWWWWWWWWWWWWWWWWWW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNSNNNNNNNNNNNSNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WWWWWWWWWWWWWWWWWWW";

        public const string TwoPlayersMap = @"
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNSNNNNNNNNNNNSNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW
WNNNNNNNNNNNNNNNNNW";
    }
}
